# Generated by Django 5.1.3 on 2024-11-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcompass', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
