# Generated by Django 5.1.3 on 2024-12-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcompass', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='courses_provided',
            field=models.ManyToManyField(blank=True, related_name='roadmaps', to='techcompass.course'),
        ),
    ]
