# Generated by Django 5.1.3 on 2024-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcompass', '0005_alter_roadmap_courses_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='progress', to='techcompass.course'),
        ),
    ]
