# Generated by Django 5.1.2 on 2024-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcompass', '0006_alter_progress_completed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='badge',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
