# Generated by Django 5.1.2 on 2024-12-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcompass', '0009_course_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_completed',
        ),
    ]
