# Generated by Django 5.1.2 on 2024-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcompass', '0010_remove_course_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='roadmap_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
